#!/usr/bin/env python3
"""
Script to help setup environment variables for AsterDex Funding Bot
"""
import os
import sys
from pathlib import Path

def setup_environment():
    """Interactive setup for environment variables"""
    
    env_file = Path(".env")
    
    print("🚀 AsterDex Funding Bot - Environment Setup")
    print("=" * 50)
    
    if env_file.exists():
        print(f"✅ Found existing .env file: {env_file.absolute()}")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📝 Please provide your AsterDex API credentials:")
    print("(You can get these from your AsterDex account settings)")
    
    api_key = input("\n🔑 Enter your API Key: ").strip()
    if not api_key:
        print("❌ API Key is required!")
        return
    
    api_secret = input("🔐 Enter your API Secret: ").strip()
    if not api_secret:
        print("❌ API Secret is required!")
        return
    
    print("\n⚙️  Optional trading configuration:")
    capital = input("💰 Capital amount in USDT (default: 200000): ").strip() or "200000"
    spot_symbol = input("📊 Spot symbol (default: ASTERUSDT): ").strip() or "ASTERUSDT"
    futures_symbol = input("📈 Futures symbol (default: ASTERUSDT): ").strip() or "ASTERUSDT"
    batch_quote = input("📦 Batch quote size (default: 200): ").strip() or "200"
    batch_delay = input("⏱️  Batch delay in seconds (default: 1.0): ").strip() or "1.0"
    mode = input("🎯 Trading mode (buy_spot_short_futures/sell_spot_long_futures, default: buy_spot_short_futures): ").strip() or "buy_spot_short_futures"
    
    # Write to .env file
    env_content = f"""# AsterDex API Configuration
# Generated by setup_env.py

ASTERDEX_API_KEY={api_key}
ASTERDEX_API_SECRET={api_secret}

# Trading Configuration
DEFAULT_CAPITAL_USD={capital}
DEFAULT_SPOT_SYMBOL={spot_symbol}
DEFAULT_FUTURES_SYMBOL={futures_symbol}
DEFAULT_BATCH_QUOTE={batch_quote}
DEFAULT_BATCH_DELAY={batch_delay}
DEFAULT_MODE={mode}
"""
    
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print(f"\n✅ Environment file created successfully: {env_file.absolute()}")
        print("\n🔒 Security Note:")
        print("- Your .env file contains sensitive API credentials")
        print("- This file is already added to .gitignore to prevent accidental commits")
        print("- Never share your API keys with anyone")
        
        print(f"\n🚀 You can now run the bot:")
        print("python3 funding_bot.py")
        print("\nOr with custom parameters:")
        print("python3 funding_bot.py --capital 5000 --batch-quote 100")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return

if __name__ == "__main__":
    setup_environment()
